public class MyHasher extends Hasher
{
	/**
		Hashing a given object without using Object's built-in
		hashcode function.
		@param obj The object to be hashed
		@return int value generated by hashing the object 
	*/
	public int hash(Object obj)
	{
		String helper = obj.toString();
		int sum = 0;
		for (int i = 0; i < helper.length(); i++)
		{
			if (i % 2 == 0)
				sum = sum + (((int)helper.charAt(i) * 5) + 8) * 7;	
			sum = sum + (((int)helper.charAt(i) * 11) + 53) * -17;
		}
		if (helper.length() % 2 == 0)
			sum = (sum + 4) * 7;
		if (helper.length() % 2 != 0)
			sum = (sum + 6) * -11;
		if (helper.length() % 3 == 0)
			sum = (sum - 14) * 19;
		if (sum % 2 == 0)
			sum = (sum - 83) * 43;
		if (sum % 2 != 0)
			sum = (sum * -8) * 11;
		if (sum % 3 == 0)
			sum = (sum * 14) + 85;
		if (obj instanceof String)
			sum = (sum - 8) * - 83;
		if (obj instanceof Integer)
			sum = (sum - 79) * 17;
		if (obj instanceof Boolean)
			sum = (sum * 21) - 48;
		return sum;
	}
	
	/**
		Simple function to identify the coder.
		@return String that is your name.
	*/
	public String getCoderName()
	{
		return "Sam Scherl";
	}
}